apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - tenancy.yaml
  - kyverno-application.yaml
  - kyverno-policies.yaml
  - observability-namespace.yaml
  - prometheus-application.yaml
  - otel-collector-application.yaml
  - observability-workload.yaml
  - observability-dashboard.yaml
