apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.8.2
    helm:
      values: |
        defaultRules:
          create: false
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeProxy:
          enabled: false
        kubeScheduler:
          enabled: false
        grafana:
          persistence:
            enabled: false
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
        prometheus:
          prometheusSpec:
            retention: 24h
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
            additionalScrapeConfigs:
              - job_name: otel-collector
                scrape_interval: 15s
                static_configs:
                  - targets:
                      - otel-collector.observability.svc.cluster.local:8888
              - job_name: otel-exported-metrics
                scrape_interval: 15s
                static_configs:
                  - targets:
                      - otel-collector.observability.svc.cluster.local:8889
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
