apiVersion: v1
kind: Pod
metadata:
  name: deny-privileged-demo
  namespace: tenant-a
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: app
      image: nginx:1.27-alpine
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
